
server:
  port: 8070

spring:
  datasource-mysql:
    driver-class-name: org.mariadb.jdbc.Driver
    jdbc-url: jdbc:mariadb://localhost:3306/test?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: zaqxsw2145
  datasource-h2:
    driver-class-name: org.h2.Driver 
    jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;
    username: sa
    password: 

 
logging:
  file:
    name: C:\Users\rudxo\log\test.log  # 로깅 파일 위치이다.
    max-history: 7 # 로그 파일 삭제 주기이다. 7일 이후 로그는 삭제한다.
    max-size: 10MB  # 로그 파일 하나당 최대 파일 사이즈이다.
  level:  # 각 package 별로 로깅 레벨을 지정할 수 있다.
    com.mybatis.demo.interceptor : debug