

spring:
  datasource-mysql:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://test:3306/test?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: test
    password: test
