
server:
  port: 8070

spring:
  datasource-mysql:
    driver-class-name: org.mariadb.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/test
    username: root
    password: zaqxsw2145
  datasource-h2:
    driver-class-name: org.h2.Driver 
    jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;
    username: sa
    password: 

  